### ISSUE TITLE
關於VOX轉KSH的問題

### ISSUE THREAD

**Issue by HMH0726** [rmstZ/rmstZ.github.io#1]
請問這個工具有需要使用特定的瀏覽器來開啟嗎?
因為我用VOX檔轉成K-Shoot MANIA的格式KSH時沒有出現保存的按鈕

**Comment by ExerciseBook** [comment]
New repo: 
https://github.com/lrfasd/lrfasd.github.io

**Comment by HMH0726** [comment]
您好,感謝您的回覆
我已經試過您剛剛所傳的新版本測試了但結果還是一樣沒有出現保存的按鈕
是否可以請您幫我測試呢?
https://onedrive.live.com/embed?cid=55D9298EA5C8310D&resid=55D9298EA5C8310D%21326&authkey=AKHQf8cxXWwUW5Y
謝謝

**Comment by HMH0726** [comment]
好的,謝謝!

**Comment by ExerciseBook** [comment]
来自作者的回复：
1. 暂不支持 vox 和 ksh
2. 已支持内容参见 changelog
